# Generated by Django 3.1.1 on 2020-09-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_card_number', models.CharField(max_length=16)),
                ('card_holder', models.CharField(max_length=250)),
                ('expiration_date', models.DateField()),
                ('security_code', models.CharField(blank=True, max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
