# Generated by Django 3.1.1 on 2020-09-08 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_card_number', models.CharField(max_length=19, verbose_name='credit card number')),
                ('card_holder', models.CharField(max_length=250, verbose_name='card holder')),
                ('expiration_date', models.DateField(verbose_name='expiration date')),
                ('security_code', models.CharField(blank=True, max_length=3, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='security code')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='amount')),
            ],
        ),
        migrations.DeleteModel(
            name='PaymentProcess',
        ),
    ]
